### ISSUE TITLE
Optimal Merge Pattern

### ISSUE THREAD

**Issue by opeeyum** [shivanshugarg12800/Algo_GT#107]
Optimal merge pattern: When two or more sorted files are to be merged all together to form a single file, the minimum computations are done to reach this file are known as Optimal Merge Pattern.  
It is one of the most asked algorithm questions in the technical round of placements.

**Comment by Sajal193** [comment]
Hi @opeeyum , can I work on this as a part of ongoing hacktoberfest. I do programming in C++.

**Comment by opeeyum** [comment]
I have done that in C++. You can go for any other language other than c++.

**Comment by Sajal193** [comment]
ok, I know only C++ and Java. If you've not made it in java, then I can do it.

**Comment by opeeyum** [comment]
Go for java.

**Comment by Sajal193** [comment]
Ok
