### ISSUE TITLE
Heap Sort

### ISSUE THREAD

**Issue by opeeyum** [shivanshugarg12800/Algo_GT#109]
**Is your feature making change to an existing problem/algorithm**
answer in yes or no
No

**If you are making changes, please describe the type of change in brief else NA**
NA

**Describe in brief about what new problem/algorithm addition**
A clear and concise description about the problem.
Heap Sort one the efficient sorting algorithm.

**Comment by sotiriszogos** [comment]
Hello, please assign it to me. I can do it in Java.

**Comment by shivanshugarg12800** [comment]
@sotiriszogos go for it

**Comment by sotiriszogos** [comment]
So, should I do it or not? Because you have closed the issue.
