### ISSUE TITLE
Merge two sorted lined list

### ISSUE THREAD

**Issue by opeeyum** [shivanshugarg12800/Algo_GT#110]
**Is your feature making change to an existing problem/algorithm**
answer in yes or no
No

**If you are making changes, please describe the type of change in brief else NA**
NA

**Describe in brief about what new problem/algorithm addition**
A clear and concise description about the problem.
Merge sorted linked list, it is also one of the most asked questions in placements.
Coded the recursive solution for the same.

**Comment by developer-nobita** [comment]
I would like to work on this. 
kindly assign this to me.

**Comment by opeeyum** [comment]
I have done it in c++, pickup any other language and go for it.
