### ISSUE TITLE
Find the Winner of the Circular Game - 1823 Leetcode

### ISSUE THREAD

**Issue by AyushAgrawal25** [shivanshugarg12800/Algo_GT#16]
Is your feature making change to an existing problem/algorithm
answer in yes or no

If you are making changes, please describe the type of change in brief else NA

Describe in brief about what new problem/algorithm addition
A clear and concise description about the problem.

**Comment by AyushAgrawal25** [comment]
@Nistha-tech can u please add hacktoberfest-21 label

**Comment by shivanshugarg12800** [comment]
@AyushAgrawal25 you can go on and work on this issue
