### ISSUE TITLE
Implement pow(x, n), which calculates x raised to the power n

### ISSUE THREAD

**Issue by shivani9-codes** [shivanshugarg12800/Algo_GT#18]
**Is your feature making change to an existing problem/algorithm**
answer in yes or no

**If you are making changes, please describe the type of change in brief else NA**

**Describe in brief about what new problem/algorithm addition**
A clear and concise description about the problem.

**Comment by AyushAgrawal25** [comment]
@shivani9-codes can u please assign this to me.

**Comment by shivanshugarg12800** [comment]
@shivani9-codes Thank you for making the contribution

**Comment by shivanshugarg12800** [comment]
@AyushAgrawal25 this issue is closed now, you can work on some other one or create your own.
