### ISSUE TITLE
Fibonacci Number

### ISSUE THREAD

**Issue by shivani9-codes** [shivanshugarg12800/Algo_GT#20]
**Is your feature making change to an existing problem/algorithm**
answer in yes or no

**If you are making changes, please describe the type of change in brief else NA**

**Describe in brief about what new problem/algorithm addition**
A clear and concise description about the problem.

**Comment by AyushAgrawal25** [comment]
@shivani9-codes  can u please assign this to me.

**Comment by shivanshugarg12800** [comment]
@shivani9-codes this problem already exists in the codebase, please look for some other problem/algorithm
