### ISSUE TITLE
Python Code for the existing algorithms

### ISSUE THREAD

**Issue by Priyaraj17** [shivanshugarg12800/Algo_GT#24]
**Is your feature making change to an existing problem/algorithm**
Yes

**If you are making changes, please describe the type of change in brief else NA**
The algorithms present are available in c++ and java, I would like to add the python code for the algorithms.

**Describe in brief about what new problem/algorithm addition**
Python code for all the algorithms

**Comment by shivanshugarg12800** [comment]
@Priyaraj17 You can go and create a new folder.

**Comment by Priyaraj17** [comment]
Thanks a lot, I will make a PR soon.

**Comment by Priyaraj17** [comment]
Hey, Can you please review this PR? @shivanshugarg12800

**Comment by shivanshugarg12800** [comment]
done

**Comment by Priyaraj17** [comment]
Thanks a lot
