### ISSUE TITLE
Tower of Hanoi 

### ISSUE THREAD

**Issue by anujkumar070** [shivanshugarg12800/Algo_GT#25]
**Is your feature making change to an existing problem/algorithm**
answer in yes or no

**If you are making changes, please describe the type of change in brief else NA**

**Describe in brief about what new problem/algorithm addition**
A clear and concise description about the problem.

**Comment by anujkumar070** [comment]
@shivanshugarg12800 can you assign this issue to me

**Comment by shivanshugarg12800** [comment]
@anujkumar070 This problem already exists in the code base, 
You can choose some different problem or make changes in any of the existing problem/ algorithm.

I am closing this issue for now, you can create a new one.
