### ISSUE TITLE
Binary Search Algorithm

### ISSUE THREAD

**Issue by anujkumar070** [shivanshugarg12800/Algo_GT#26]
**Is your feature making change to an existing problem/algorithm**
answer in yes or no

**If you are making changes, please describe the type of change in brief else NA**

**Describe in brief about what new problem/algorithm addition**
A clear and concise description about the problem.

**Comment by Jibendu007** [comment]
@anujkumar070  Can I be assigned?

**Comment by anujkumar070** [comment]
> @anujkumar070 Can I be assigned?

I can't assign it as I am not a maintainer of this project

**Comment by anujkumar070** [comment]
@shivanshugarg12800 Can you assign this to me?

**Comment by shivanshugarg12800** [comment]
@anujkumar070 You can go on and work on this issue.

**Comment by amanb4** [comment]
@shivanshugarg12800 can you assign this to me?

**Comment by LikhithaTadikonda** [comment]
@shivanshugarg12800 Pls assign this to me. I would like to contribute ASAP :)

**Comment by shivanshugarg12800** [comment]
@LikhithaTadikonda, @amanb4  
You surely can create your own issues and contribute easily.
