### ISSUE TITLE
LCMofTWOINTEGERS

### ISSUE THREAD

**Issue by amanb4** [shivanshugarg12800/Algo_GT#33]
**Is your feature making change to an existing problem/algorithm**
no

**If you are making changes, please describe the type of change in brief else NA**
 NA

**Describe in brief about what new problem/algorithm addition**
problem to find LCM of two integers.

**Comment by ansharora7** [comment]
Can you assign me this, please?

**Comment by shivanshugarg12800** [comment]
@amanb4 You can go and work on this issue.

**Comment by tausiq2003** [comment]
can I work on this
