### ISSUE TITLE
Dungeon Game 174 LeetCode

### ISSUE THREAD

**Issue by AyushAgrawal25** [shivanshugarg12800/Algo_GT#34]
**Is your feature making change to an existing problem/algorithm**
answer in yes or no

**If you are making changes, please describe the type of change in brief else NA**

**Describe in brief about what new problem/algorithm addition**
A clear and concise description about the problem.

**Comment by AyushAgrawal25** [comment]
@shivani9-codes can u assign this to me. I really want to share my solution.

**Comment by shivanshugarg12800** [comment]
@AyushAgrawal25 You can go and work on this issue.
