### ISSUE TITLE
Rod Cutting Problem (DP)

### ISSUE THREAD

**Issue by ansharora7** [shivanshugarg12800/Algo_GT#35]
**Is your feature making change to an existing problem/algorithm**
No

**If you are making changes, please describe the type of change in brief else NA**

**Describe in brief about what new problem/algorithm addition**
Given the price of different sub-lengths of a rod, find the optimal way to cut the rod to get the maximum price

**Comment by ansharora7** [comment]
Can you assign me this please?

**Comment by shivanshugarg12800** [comment]
Happy Contributing @ansharora7
