### ISSUE TITLE
Binary to Gray code using recursion

### ISSUE THREAD

**Issue by shivani9-codes** [shivanshugarg12800/Algo_GT#37]
**Is your feature making change to an existing problem/algorithm**
answer in yes or no

**If you are making changes, please describe the type of change in brief else NA**

**Describe in brief about what new problem/algorithm addition**
A clear and concise description about the problem.

**Comment by tausiq2003** [comment]
should I do this

**Comment by shivanshugarg12800** [comment]
@tausiq2003 this issue is closed, you can go on, create another and make contribution.
