### ISSUE TITLE
Smaller numbers to left 

### ISSUE THREAD

**Issue by Niyati3031** [shivanshugarg12800/Algo_GT#40]
**Is your feature making change to an existing problem/algorithm**
Yes

**If you are making changes, please describe the type of change in brief else NA**
I will add a problem of leetcode smaller numbers in java folder.

**Describe in brief about what new problem/algorithm addition**
Here we use merge sort algorithm to find the number of smaller numbers to right to number in given array.

Please assign this to me @shivanshugarg12800

**Comment by Niyati3031** [comment]
Please assign me this

**Comment by shivanshugarg12800** [comment]
@Niyati3031 Congratulations on creating your first issue
You can go and work on this.
