### ISSUE TITLE
Strassen’s matrix multiplication algorithm

### ISSUE THREAD

**Issue by ansharora7** [shivanshugarg12800/Algo_GT#47]
**Is your feature making change to an existing problem/algorithm**
No

**If you are making changes, please describe the type of change in brief else NA**

**Describe in brief about what new problem/algorithm addition**
Adding Strassen’s matrix multiplication algorithm to multiply two matrices

**Comment by ansharora7** [comment]
Please assign this to me.

**Comment by shivanshugarg12800** [comment]
@ansharora7 you can work on this issue on now.
