### ISSUE TITLE
FindKthBithInNthString java file

### ISSUE THREAD

**Issue by Niyati3031** [shivanshugarg12800/Algo_GT#50]
**Is your feature making change to an existing problem/algorithm**
yes

**If you are making changes, please describe the type of change in brief else NA**
I will add a problem of leetcode named findkthbitinnthstring in java folder.

**Describe in brief about what new problem/algorithm addition**
this problem uses recursion.

please assign this to me @shivanshugarg12800

**Comment by Lightning-Nemesis** [comment]
Hey , 
Can you please assign this issue to me?

**Comment by shivanshugarg12800** [comment]
@Niyati3031 You can work on this.

**Comment by Niyati3031** [comment]
hey @shivanshugarg12800 i mistakenly added this file also with my previous pr which just got merged can you please deleted recursion folder so that i can make pr for this issue

**Comment by Niyati3031** [comment]
please can you help..

**Comment by Niyati3031** [comment]
or if you allow i can delete that folder and make a new folder with solution for pr @shivanshugarg12800

**Comment by shivanshugarg12800** [comment]
i have deleted that Recursion folder in Java @Niyati3031

**Comment by shivanshugarg12800** [comment]
You can work on this issue.

**Comment by Niyati3031** [comment]
check my pr
