### ISSUE TITLE
Conway's game of life

### ISSUE THREAD

**Issue by ansharora7** [shivanshugarg12800/Algo_GT#52]
**Is your feature making change to an existing problem/algorithm**
No

**If you are making changes, please describe the type of change in brief else NA**

**Describe in brief about what new problem/algorithm addition**
A very famous game created by John Horton Conway. It is a zero-player game. It is a fundamental part of DSA.

**Comment by ansharora7** [comment]
Please assign me this.

**Comment by shivanshugarg12800** [comment]
@ansharora7 You can work on this.
