### ISSUE TITLE
Bounded-Knapsack Unbounded-knapsack DP

### ISSUE THREAD

**Issue by utsaverma2001-crypto** [shivanshugarg12800/Algo_GT#9]
**Is your feature making change to an existing problem/algorithm**
NO

**If you are making changes, please describe the type of change in brief else NA**
NA

**Describe in brief about what new problem/algorithm addition**
Knapsack and Unbounded Knapsack are two basic strategies for solving questions of DP. Here the problem is of type: we have to select values from n bags having different values each. We have to decide which bag to choose k bags out of n so that our bag gets maximum value. This problem requires optimization and have recursive calls so require DP.

**Comment by shivanshugarg12800** [comment]
Hi @utsaverma2001-crypto ,you can go ahead make your PR.
